language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev

install:
  - "pip install -r requirements-dev.txt"

# command to run tests
script: nosetests -v

after_success:
  - codecov

notifications:
#  email:
#    recipients:
#      - pywikibot-commits@lists.wikimedia.org
#    on_success: always
#    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#pywikibot"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
